### ISSUE TITLE
Help with running the script

### ISSUE THREAD

**Issue by kzzyn** [tccoin/Jellyfin-Potplayer#1]
I am trying to get this to work. I am not a developer, just a user. 
I am using the latest stable installer version of jellyfin on Windows Home.
1)
I downloaded your files and extracted them into folder, changed path to potplayer.ps1 in potplayer.reg and ran the reg file (I checked the registry, the new values are there).
2)
I installed Tampermonkey to Firefox (and tried Vivaldi, too), installed the script and changed the path to the jellyfin web-ui at the top.
There are three yellow exclamation marks. They say that ConnectionManager and ApiClient are not defined:
![script_ex_01](https://user-images.githubusercontent.com/52583076/92326559-46dc0e80-f053-11ea-921b-ac1688ab4723.png)

I enabled the script and tried to play some videos but there is just a brief pop-up of blue (powershell) window, which closes immediately.

Will you please help? Can I do something to help troubleshoot this?
I would really like to get this running.
Thanks.

edit:
or do I have to put the script in the installation folder of jellyfin ?

**Comment by tccoin** [comment]
Hi kyyzn, did you edit the path in potplayer.reg? If you didn't, please change `C:\\Users\\Tccoin\\Codes\\jellyfin-potplayer\\potplayer.ps1` to your own path of "potplayer.ps1."

**Comment by tccoin** [comment]
And also, you may want to change this part in the js script:
```let path = r.Path.replace(/\\/g, '/').replace('D:', 'Z:');```
into:
```let path = r.Path.replace(/\\/g, '/');```
the "replace" function is to correct the drive letter and it may not suit your situation. For me, I have the Jellyfin server on the NAS and I want to play the video directly on my laptop. Thus I assign Z: to the NAS drive on my laptop and use this script to replace D: (which is the drive letter on NAS) in the video path to Z: (which is the drive letter on my laptop). The final path will be passed to Potplayer.

**Comment by kzzyn** [comment]
thank you for your time, tccoin.
I changed the path in reg file and also changed the js script (deleted ".replace('D:', 'Z:')", but it is still not working. 
the blue (powershell) window pops-up for longer time now :)

I have found this in windows event viewer about powershell:
![script_ex_02](https://user-images.githubusercontent.com/52583076/92773951-51710d80-f39d-11ea-865a-9a0e99cc15a7.png)

could this be the problem ? the path ?

**Comment by tccoin** [comment]
@kzzyn In my opinion, assigning a letter to \\Codex will be much easier. Just right click the icon of "This Computer" and choose the menu named "add a network location" (or something similar to it).

**Comment by kzzyn** [comment]
yes, after assigning letter to the folder on NAS it works. 
Thank you.

**Comment by tccoin** [comment]
You are welcome.

**Comment by hestenet** [comment]
I apologize for bumping a very old issue, let me know if you would like me to open a new issue instead.

I am having the same problem with ` ConnectionManager is undefined` and `ApiClient is undefined`.

![image](https://user-images.githubusercontent.com/6272622/121793902-84f4f880-cbb8-11eb-8289-decf62b9618b.png)

The regedit successful added the potplayer:// protocol handling, and if I directly enter an address like:
`potplayer://localhost:8096/Items/a0e731206375627cda2e34fad7589610/Download?api_key=d948b800b182411799c525225aa2bd18` into the browser, the powershell script successfully runs and the video content plays. 

But if I simply click to play, nothing happens in the browser and in the browser console I see these errors: 
![image](https://user-images.githubusercontent.com/6272622/121793977-3b58dd80-cbb9-11eb-93d4-0bfcf3e339fd.png)



I cannot tell from the thread above how the `undefined` errors were solved.  Thanks for any help.

**Comment by tccoin** [comment]
> I apologize for bumping a very old issue, let me know if you would like me to open a new issue instead.
> 
> I am having the same problem with ` ConnectionManager is undefined` and `ApiClient is undefined`.
> 
> ![image](https://user-images.githubusercontent.com/6272622/121793902-84f4f880-cbb8-11eb-8289-decf62b9618b.png)
> 
> The regedit successful added the potplayer:// protocol handling, and if I directly enter an address like:
> `potplayer://localhost:8096/Items/a0e731206375627cda2e34fad7589610/Download?api_key=d948b800b182411799c525225aa2bd18` into the browser, the powershell script successfully runs and the video content plays.
> 
> But if I simply click to play, nothing happens in the browser and in the browser console I see these errors:
> ![image](https://user-images.githubusercontent.com/6272622/121793977-3b58dd80-cbb9-11eb-93d4-0bfcf3e339fd.png)
> 
> I cannot tell from the thread above how the `undefined` errors were solved. Thanks for any help.

Yes, please open a new issue. I will look into this problem right now.

**Comment by hestenet** [comment]
Opened issue #3 

Re: Jellyfin version - I was using: 10.7.5 - the [latest windows stable](https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.7.5_windows-x64.exe).
