### ISSUE TITLE
Invalid path when path or file name is in Chinese (中文路径名问题)

### ISSUE THREAD

**Issue by WShiBee** [tccoin/Jellyfin-Potplayer#12]
When path or file name contains Chinese, the path output to potplayer will be garbled. 
![02](https://user-images.githubusercontent.com/107931613/174804389-8f565901-2fc4-40d4-b56c-7adb1a9823c0.PNG)
 
All in English, potplayer will run smoothly. 

只要路径或文件名里有中文就不行。

**Comment by SEANTAMXX** [comment]
试试脚本里用encodeURI
比如 window.open('potplayer://' + encodeURI(path))

**Comment by WShiBee** [comment]
搞定了，升级了potpalyer后，需要重新合并注册表就可以了。

**Comment by OHLIA** [comment]
@WShiBee 请教一下，合并注册表具体是如何做？

**Comment by tccoin** [comment]
@OHLIA 我看到你图片里的脚本有语法错误，把Javascript:删掉试一下？

**Comment by OHLIA** [comment]
> @OHLIA 我看到你图片里的脚本有语法错误，把Javascript:删掉试一下？

谢谢指正，但是我删除后，还是无法解决问题。
