### ISSUE TITLE
How to use this script? Cloud you please write some documents?

### ISSUE THREAD

**Issue by zhu327** [tccoin/Jellyfin-Potplayer#2]

**Comment by tccoin** [comment]
Okay, I will. Maybe next week?

**Comment by tccoin** [comment]
Hi, I have updated the readme file, so I'll close this issue for now. Please read the installation part for help. If you encounter some problems, feel free to ask me by opening another issue.

Notice that the script may not work with a newer version of Jellyfin as mention in #1 and I'll work into it these days.
