### ISSUE TITLE
ConnectionManager is undefined and ApiClient is undefined in userscript.js

### ISSUE THREAD

**Issue by hestenet** [tccoin/Jellyfin-Potplayer#3]
As requested - opening a new issue for this:

I am having a problem with ` ConnectionManager is undefined` and `ApiClient is undefined`.

![image](https://user-images.githubusercontent.com/6272622/121793902-84f4f880-cbb8-11eb-8289-decf62b9618b.png)

The regedit successful added the potplayer:// protocol handling, and if I directly enter an address like:
`potplayer://localhost:8096/Items/a0e731206375627cda2e34fad7589610/Download?api_key=d948b800b182411799c525225aa2bd18` into the browser, the powershell script successfully runs and the video content plays. 

But if I simply click to play, nothing happens in the browser and in the browser console I see these errors: 
![image](https://user-images.githubusercontent.com/6272622/121793977-3b58dd80-cbb9-11eb-93d4-0bfcf3e339fd.png)

I cannot tell from the thread above how the `undefined` errors were solved.  Thanks for any help.

_Originally posted by @hestenet in https://github.com/tccoin/Jellyfin-Potplayer/issues/1#issuecomment-860143272_

**Comment by hestenet** [comment]
Re: Jellyfin version - I was using: 10.7.5 - the [latest windows stable](https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.7.5_windows-x64.exe).

**Comment by ansonhorse** [comment]
> Re: Jellyfin version - I was using: 10.7.5 - the [latest windows stable](https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.7.5_windows-x64.exe).

You may try this:
```js
let openPotplayer = async (itemid) => {
    let userid = (await ApiClient.getCurrentUser()).Id;
....
```

**Comment by tccoin** [comment]
> > Re: Jellyfin version - I was using: 10.7.5 - the [latest windows stable](https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.7.5_windows-x64.exe).
> 
> You may try this:
> 
> ```js
> let openPotplayer = async (itemid) => {
>     let userid = (await ApiClient.getCurrentUser()).Id;
> ....
> ```

I've tested your codes in both the old and new versions of Jellyfin and it works! Great Job! I've updated the script. @hestenet Please update the user script in userscript.js and it should work fine now.

**Comment by Zachhambo** [comment]
I am having the same issue, but only ApiClient not defined, on windows Jellyfin 10.8.9

**Comment by Yossik19** [comment]
> I am having the same issue, but only ApiClient not defined, on windows Jellyfin 10.8.9

Try this one. Fresh and working [PPJF](https://github.com/Damocles-fr/PPJF)

**Comment by Zachhambo** [comment]
> > I am having the same issue, but only ApiClient not defined, on windows Jellyfin 10.8.9
> 
> Try this one. Fresh and working [PPJF](https://github.com/Damocles-fr/PPJF)

Wow thanks!
