### ISSUE TITLE
how to setting {path = path.replace('/', 'v:');}

### ISSUE THREAD

**Issue by kitkw** [tccoin/Jellyfin-Potplayer#7]
![Screenshot 2022-02-26 061648](https://user-images.githubusercontent.com/31963066/155810826-eea4269c-1a27-4b3c-8701-6d133e98d2b9.jpg)
![061244](https://user-images.githubusercontent.com/31963066/155812389-b70d30f6-8ec9-4117-97e2-771095a2bc73.jpg)
![061433](https://user-images.githubusercontent.com/31963066/155810841-e8f71fcf-660a-473f-be99-43d107bc9522.jpg)
![Screenshot 2022-02-25 214748](https://user-images.githubusercontent.com/31963066/155810853-63c6d332-36bd-46ac-b143-5c1340cee836.jpg)

**Comment by tccoin** [comment]
In this case, you may want to try `path = 'V:'+path.replace(/\//g,'\\')`. Let me know if you any other questions.

**Comment by kitkw** [comment]
> In this case, you may want to try `path = 'V:'+path.replace(/\//g,'\\')`. Let me know if you any other questions.

like this?? It's not work.
![11](https://user-images.githubusercontent.com/31963066/155815746-378528f6-b73b-4de6-9595-4bd82742d285.jpg)

**Comment by tccoin** [comment]
Can you open F12 developer tool in the Jellyfin and then check the output in the console? You can adjust the script according to how the output looks like.

**Comment by kitkw** [comment]
> Did you modify other scrips? I am not sure where does the additional backslash come from...

I did not modify other scripts. 
![155861901-8813fb7a-9193-4918-a072-2d52e6b98298](https://user-images.githubusercontent.com/31963066/155863624-09915571-a59e-4e61-82e0-1b269338fb92.jpg)

**Comment by tccoin** [comment]
你好，我看到你系统是中文的就直接回复中文咯，这位朋友第二条里提到了解决的办法：https://github.com/tccoin/Jellyfin-Potplayer/issues/11
